MaRDI4NFDI/python-zbMathRest2Oai

getPublicationInfo.py
pyproject.toml

Test API request v0

---

src/zbmath_rest2oai/writeOai.py

**Changes**:
- add functional example

Fix oai toy example

---

src/zbmath_rest2oai/getWithSwagger.py

* normalize ws according to black suggestions
* fix name of id element

Style corrections

---

formats/createFormats.sh

Add non working example of format creation

---

test/data/articles/plain.xml

Generate new refrence

---

src/zbmath_rest2oai/get_all.py
src/zbmath_rest2oai/run_get_all_de_documents.py
src/zbmath_rest2oai/run_get_all_de_software.py
src/zbmath_rest2oai/state.py
src/zbmath_rest2oai/writeOai.py
src/zbmath_rest2oai/write_documents_2_Oai.sh
src/zbmath_rest2oai/write_software_2_Oai.sh

* Add state class (quick and dirty with ChatGPT)
* Refactor getting all software and documents
**Changes**:
- 
- 
-  

Optimize state handling

---

test/data/software/Sagemath_plain.xml
test/data/software/Test_Result_Codemeta.xml
test/test_metadata_software_Codemeta.py
xslt/software/xslt-software-Codemeta.xslt

**Changes**:
- xslt to transform the metadata of the software to codemeta schema 
-the plain xml that should be transformed 
-  the result of the transformation also as an xml 
- a unittest in python to test the implementation

Xslt software to code meta

---

test/test_metadata_article_OpenAire.py
test/test_metadata_software_Codemeta.py

**Changes**:
- adjusting the file paths in test_metadata_software_OpenAire.py to fix the unittest issue
- adjusting also the paths of the other files in the other unittests. 
-  

Fixing unittests

---

test/data/software/plain.xml

…api version
**Changes**:
- a new Api version leads to new plain.xml of software metadata 
- merging the differences and new changes of the plain.xml to be up to date

updating the plain.xml for software metadata 

---

test/data/software/Test_Result_Codemeta.xml
xslt/software/xslt-software-Codemeta.xslt

**Changes**:
- changing the id to a real uri 
- adjusting the identifier - categoryCode and nubmerofItems
-  applying these changes in the reference and the xslt

Xslt dev code meta

---

src/zbmath_rest2oai/restApi_software_Json.py

…th of the output for json
**Changes**:
- updating the url for swh metadata provenance
- adjusting the path of the output file swhid.json
-

upadting the code of rest_apisoftware

---

xslt/software/xslt-software-Codemeta.xslt

**Changes**:
- changing the url of the references in the xslt code  such it can generate the identifiers of the refnerences with its zbmath rest api url 
- 
-

adding the url of api to the references Identifiers

---

test/data/software/OpenAire-software-reference.xml
xslt/software/xslt-software-OpenAire.xslt

**Changes**
- xslt and xml files for OpenAire  (adjsuting the resourceType)
- 
-

Fix open aire

---

test/data/software/Test_Result_Codemeta.xml
xslt/software/xslt-software-Codemeta.xslt

**Changes**:
- adjusting the identifiers by adding the swmath.org url to the identifiers in supporting data property , both in xslt and xml

adjusting the identifiers 

---

test/data/software/Test_Result_Codemeta.xml
xslt/software/xslt-software-Codemeta.xslt

**Changes**:
- adding the character  ( / )  in xslt and xml of codemeta to schema.org namespace to fix the bug
- 
-

Fix codemeta supportingdata

---

test/data/software/Test_Result_Codemeta.xml
xslt/software/xslt-software-Codemeta.xslt
xslt/software/xslt_SWH_deposit.xslt

**Changes**:
- removing the categoryCode (classification) of codemeta in xslt and xml 
- adjusting the url of schema.org in the xslt for swh deposit. 
-

Codemeta adjustments

---

test/data/software/Test_Result_Codemeta.xml
xslt/software/xslt-software-Codemeta.xslt
xslt/software/xslt_SWH_deposit.xslt

**Changes**
- instead of editing the pipeline , i just adjusted the identifier in the main xslt and the reference.xml for codemeta 
such we can adjust it easily in the pipeline and take the result from the main xslt-software-codemeta without any further changes 
-  
i will wait for your review and opinion , i chose this solution for it

Editing the identifier for software-codemeta

---

xslt/software/xslt_SWH_deposit.xslt

**Changes**:
- deleting the line select copy of id 
- writing a template for id transformation in xslt , that transform the id node from oai-pmh server to the desired result for codemeta

adjusting the (id) property in the xslt

---

xslt/software/xslt_SWH_deposit.xslt

**Changes**:
- adjusting the id template in the xslt to generate a correct id property 
- 
-

adjusting the id template to fix the bug

---

test/data/software/Datacite-software-reference.xml
xslt/software/xslt-software-datacite.xslt

**Changes**:
- adjusting the template of relatedIdentifiers especially the word from ARXIV to arXiv to match with the datacite requirements and chaning it also in the reference.xml file 
- 
-

Datacite-tiny- software fix

---

test/data/software/OpenAire-software-reference.xml
xslt/software/xslt-software-OpenAire.xslt

**Changes**:
- adjusting the xslt  template of alternateIdentifiers by adding the wrap node 
- adjusting the result in the targeted open-aire-software-reference.xml

Alternate identifiers open aire

---

test/data/software/Test_Result_Codemeta.xml
xslt/software/xslt-software-Codemeta.xslt
xslt/software/xslt-software-OpenAire.xslt

**Changes**:
- adding the conditional statement to alternate identifiers to avoid empty  not wanted results
- 
-

adding the condition for alternate identifiers

---

xslt/software/xslt_SWH_deposit.xslt

**Changes**:
- added the property referncePublication to the xslt of swh_deposit so it could be extracted with the result from oai records.

referncePublication deposit

---

test/data/software/Datacite-software-reference.xml
test/data/software/OpenAire-software-reference.xml
test/data/software/plain_with_references.xml
xslt/software/xslt_SWH_deposit.xslt

**Changes**:
- adjusting the part of codemeta url in xslt for codemeta to have this result <codemeta:url>https://staging.swmath.org/11234</codemeta:url> and remove the prefix oai:swmath:org from the depositing result.

correct the condition of the template for the url

---

src/zbmath_rest2oai/getAsXml.py

**Changes**:
- reshape the if condition in extract tags function in the getAsXml.py
such we can retrieve the records of JFM  and ZBL from the database 
- i could include also ARXIV and ERAM when needed 
-  i could also include the extracted records in the openaire set.

extract the records of zbl from database

---

src/zbmath_rest2oai/getAsXml.py

**Changes**:
- some correcetions to the function , because the ingestion to the set was not showing any records.
-

correcting the function
